### ISSUE TITLE
A cosa serve il menù gerarchico

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#101]
Nella sezione 5.1, pag. 22, descrivere a quale fine è stato utilizzato un menù gerarchico, perferibilemnt eprima della frase "Nel progetto il menù gerarchico è creato dinamicamente"

**Comment by andreacostazza** [comment]
Nel progetto il menù gerarchico ha lo scopo di raggruppare gli uffici della base di conoscenza relativa alla macrostruttura del Comune di Catania, sotto forma di struttura ad albero gerarchico. Esso è creato dinamicamente, cioè ad ogni valore che viene passato si controlla il genitore e i figli associati.

**Comment by andreacostazza** [comment]
bca222fc3c6c5fad6f8e766ce20f2b84a49c8a41
