### ISSUE TITLE
Descrivere meglio la classe Description

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#105]
pag.22 
Cosa rappresenta una istanza di questa classe? Come viene usata nel progetto?

**Comment by andreacostazza** [comment]
Classe Description, in questa classe ad ogni ufficio appartenete alla base di conoscenza della macrostruttura del Comune di Catania, viene associato tre variabili che sono:
uri: corrispondente al suo indirizzo IRI/URI;
name: corrispondente al suo nome;
homepage: corrispondente alla sua homepage, che si collega alla pagina principale del sito web.

**Comment by andreacostazza** [comment]
bca222fc3c6c5fad6f8e766ce20f2b84a49c8a41
