### ISSUE TITLE
homepage nella description

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#106]
Sempre a pagina 22 "homepage: Indirizzi IRI/URI che si collega alla pagina principale del sito web"

di quale sito web si sta parlando? spiegare.

**Comment by andreacostazza** [comment]
homepage: Indirizzi IRI/URI che si collega alla pagina principale del sito web di uno degli uffici della macrostruttura del Comune di Catania

**Comment by andreacostazza** [comment]
bca222fc3c6c5fad6f8e766ce20f2b84a49c8a41
