### ISSUE TITLE
onreadystatechange quale funzione chiama?

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#113]
pag.26
"La variabile onreadystatechange chiama la funzione ogni volta che il valore ottenuto dal metodo
readyState cambia." Quale funzione chiama? Come fa una variabile a chiamare una funzione?

**Comment by andreacostazza** [comment]
Alla variabile onreadystatechange viene associata una funzione; tale funzione dipende dal valore assunto dal metodo readyState.

**Comment by andreacostazza** [comment]
bca222fc3c6c5fad6f8e766ce20f2b84a49c8a41
