### ISSUE TITLE
Enumerare tutte le sezioni successive alla 1 nell'introduzione

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#125]
L'introduzione deve chiudersi con l'elenco di tutte le sezioni. Una cosa del tipo: "Il resto della tesi è strutturato come segue: nella Sezione 2 vedremo i concetti base del web semantico, la Sezione 3 riguarda ..."

**Comment by andreacostazza** [comment]
bca222fc3c6c5fad6f8e766ce20f2b84a49c8a41
