### ISSUE TITLE
passare come parametro la sotto-organizzazione selezionata quando si clicca su un elemento del menù

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#127]
Gli elementi del menù gerarchico sono dei link che devono puntare alla stessa pagina, aggiungendo però alla uri un parametro select che conterrà la URI dell'individuo corrispondente all'area o ufficio (o comune) selezionato.

**Comment by andreacostazza** [comment]
f4bfd3e97ee07e4d20ccd8ab6887bb5c04ef4c4a
