### ISSUE TITLE
mostrare solo gli uffici selezionati se presente il parametro select

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#128]
Quando la pagina viene caricata, se è presente il parametro select nella url invocata, selezionare tutti gli uffici che sono in relazione http://www.w3.org/ns/org#transitiveSubOrganizationOf con l'elemento selezionato, se si tratta di un'area. Considerare il caso di foglie.

**Comment by andreacostazza** [comment]
12d2f4072184f7d64a3879777fe7a7ac548fd9ae
