### ISSUE TITLE
la chiusura riflessiva di transitiveSuborganizationOf non funziona

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#130]
Sono state inserite le due direttive indicate di seguito ma ransitiveReflexiveSubOrganizationOf non sembra essere riflessiva.

<owl:ObjectProperty rdf:about="&org;transitiveReflexiveSubOrganizationOf">
        <rdf:type rdf:resource="&owl;ReflexiveObjectProperty"/>
    /owl:ObjectProperty

```
<rdf:Description rdf:about="&org;transitiveSubOrganizationOf">
    <rdfs:subPropertyOf rdf:resource="&org;transitiveReflexiveSubOrganizationOf"/>
</rdf:Description>
```

**Comment by andreacostazza** [comment]
846cab9a682c9ec8164775c767e869f77e50b76b
