### ISSUE TITLE
Aggiungere riferimenti al sito del W3C

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#20]
Aggiungerlo come nota a piè di pagina qui "non solo ha ideato il Word Wide
Web(WWW) e il W3C(World Wide Web Consortium)". Usare l'environment \url

**Comment by andreacostazza** [comment]
Cosa significa usare l'environment \url?

**Comment by andreacostazza** [comment]
Adesso ho capito è un comando latex

**Comment by andreacostazza** [comment]
a62d73f8befa9791956ac48215d075f69c814ebd
