### ISSUE TITLE
Errato riferimento ai sistemi di rappresentazione della conoscenza

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#25]
pag. 6 "A tal proposito venne introdotto il concetto di rappresentazione della conoscenza".
Lo studio dei sistemi di rappresentazione della conoscenza è precedente al web semantico, qui gli strumenti che fornisce vengono semplicemente utilizzati.

**Comment by andreacostazza** [comment]
sostituito "venne introdotto" con "si utilizza"

**Comment by andreacostazza** [comment]
a62d73f8befa9791956ac48215d075f69c814ebd
