### ISSUE TITLE
Riformulare la parte sui sistemi di rappresentazione della conoscenza evitando riferimenti al ragionamento umano

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#27]
Pag.6 "A tal proposito venne introdotto il concetto di
rappresentazione della conoscenza, che consisteva nell’immettere
il ragionamento umano dentro le macchine attraverso dei simbolismi,
cioè regole e operandi in modo che potessero essere in grado di pro-
cessare l’informazione; in altre parole dotare ai personal computer la
capacità di ragionare come l’essere umano."

I sistemi di rappresentazione della conoscenza permettono di usare semantiche formali e simbolismi di carattere matematico. La seguente frase va bene

"regole e operandi in modo che potessero essere in grado di pro-
cessare l’informazione"

Eliminare in tutta la tesi ogni riferimento al ragionamento umano.

**Comment by andreacostazza** [comment]
Sostituito con il seguente concetto
"A tal proposito si utilizza il concetto di rappresentazione della conoscenza.
I sistemi di rappresentazione della conoscenza permettono di usare semantiche formali e simbolismi di carattere matematico, cioè una serie di costrutti sia per definire la sintassi del dominio di interesse, sia una serie di operatori che permettano di dare un significato alle asserzioni."
