### ISSUE TITLE
note a piè di pagina vanno messe dopo la punteggiatura

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#28]
Ad esempio "Con questo ragionamento possiamo quindi costruire una base di conoscenza\footnote{...},"
dovrebbe essere "Con questo ragionamento possiamo quindi costruire una base di conoscenza,\footnote{...}"

Verificare in tutta la tesi e correggere

**Comment by andreacostazza** [comment]
a62d73f8befa9791956ac48215d075f69c814ebd

**Comment by cristianolongo** [comment]
Vedi Nota 4 a pagina 7 dopo rappresentazione della conoscenza

**Comment by andreacostazza** [comment]
bca222fc3c6c5fad6f8e766ce20f2b84a49c8a41
