### ISSUE TITLE
La base di conoscenza non è realizzata in SPARQL

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#32]
Pag.6 "In questo progetto si utilizza un base di conoscenza realizzata in SPARQL" -> ""In questo progetto si utilizza un base di conoscenza realizzata in RDF (vedi Sezione \ref{...})"

Al posto dei ... metti la label associata alla sezione che descrive RDF.

**Comment by andreacostazza** [comment]
Sostituito Sezione con Paragrafo

**Comment by andreacostazza** [comment]
a62d73f8befa9791956ac48215d075f69c814ebd
