### ISSUE TITLE
Il triplestore e SPARQL si riferiscono a RDF

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#40]
a pagina 8 nella sezione su RDF "Queste
risorse possono essere salvate in un storage di triple che vengono
successivamente elaborati con il linguaggio SPARQL."

Innanzitutto "vengono" è sbagliato. 

Inoltre, queste affermazioni sono già vere per i grafi RDF. Quindi spostare questa parte nell'item relativo a RDF o eliminarla del tutto.

**Comment by andreacostazza** [comment]
Eliminata

**Comment by andreacostazza** [comment]
a62d73f8befa9791956ac48215d075f69c814ebd
