### ISSUE TITLE
Introduzione al grafo in figura tre

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#49]
Pag.9 il paragrafo dopo il grafo in figura 3 inizia con "che si traduce nel linguaggio rdf:" il che grammaticamente non ha senso. "Sostituire con "Il grafo indicato in Figura \ref{label della figura} si traduce nel linguaggio rdf come segue:"

**Comment by andreacostazza** [comment]
7d0d09a81f1644a71f9958edf78253130558c273
