### ISSUE TITLE
Indicare le proprietà in minuscolo

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#50]
Per convenzione generalmente accettata le proprietà e gli individui vanno indicati con la lettera minuscola, mentre le classi con la prima lettera maiuscola. Ad esempio, a Pag.9 le proprietà "Personaggio", "Nome" e "Luogo di Nascita" dovrebbero essere "personaggio", "nome" e "luogodinascita" (senza spazi). Verificare che la convenzione sia rispettata in tutta la tesi.

**Comment by andreacostazza** [comment]
7d0d09a81f1644a71f9958edf78253130558c273
