### ISSUE TITLE
Non usare il termine "insieme" per i container

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#52]
Pag. 10 - "Un’ altra caratteristica importante del modello RDF e che è le risorse possono essere raggruppate per formare un insieme; tale insieme prende il nome di Contenitore e in RDF può essere di tre tipi:"

In questo caso il termine insieme è fuorviante. Sia perchè anche le classi in realtà sono insiemi, sia perchè gli insiemi nel senso della teoria degli insiemi di Zermelo-Frenkel non sono ordinati, come lo sono ad esempio i Sequence citati sotto. Proporrei di riscrivere la frase in questione come segue:

"Un’ altra caratteristica importante del modello RDF e che è le risorse possono essere raggruppate in strutture che prendono il nome di Contenitori. In RDF un contenitore può essere di tre tipi:"

**Comment by andreacostazza** [comment]
7d0d09a81f1644a71f9958edf78253130558c273
