### ISSUE TITLE
Eliminare i riferimenti al linguaggio Java nella descrizione di RDF

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#55]
"Il sistema di classi e delle proprietà di RDF Schema è simile al linguaggio Java" questo può creare confusione perchè il modello ad Oggetti è ad albero, mentre i modelli basati sui sistemi di rappresentazione della conoscenza non lo sono.

**Comment by andreacostazza** [comment]
7d0d09a81f1644a71f9958edf78253130558c273
