### ISSUE TITLE
Riformulare la frase a pagina 9

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#64]
"Le risorse, i predicati possono essere solo URI/IRI mentre i valori però possono assumere qualsiasi
forma, le principali forme assunte sono:"

Scritta così non ha molto senso. Inoltre:
- le risorse citate all'inizio possono essere sia come soggetto che come oggetto. Forse intendevi i soggetti delle asserzioni;
- dici che quelle sono le principali forme, ce ne sono altre?

**Comment by andreacostazza** [comment]
Le risorse, i predicati possono essere solo URI/IRI mentre i valori possono essere:

**Comment by andreacostazza** [comment]
07ab072a7cf9f1f5fc301118f519f5443969fb30
