### ISSUE TITLE
RDFS non è una rappresentazione semantica di RDF

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#65]
"Per rappresentare semanticamente il modello RDF, si utilizza un’estensione chiamata RDF Schema"

è errato

**Comment by andreacostazza** [comment]
Scrivo così 
Per definire schemi e vocabolari per i metadati, si utilizza un'estensione di RDF chiamata RDF Schema

**Comment by andreacostazza** [comment]
07ab072a7cf9f1f5fc301118f519f5443969fb30
