### ISSUE TITLE
Rivedere la definizione degli individui

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#67]
A pag.11

"Individui: costanti usate solo nelle asserzioni."

Sono costanti usate "principalmente" nelle asserzioni. Esistono infatti dei costrutti OWL (detti nominals) che permettono di creare concetti a partire dagli individui. Inoltre proporrei anche di dire che rappresentano entità astratte o concrete.

**Comment by andreacostazza** [comment]
individui: entità astratte o concrete usate nelle asserzioni.

**Comment by andreacostazza** [comment]
07ab072a7cf9f1f5fc301118f519f5443969fb30
