### ISSUE TITLE
33KB di memoria per fare cosa?

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#69]
pag. 14 "una semplice e versatile libreria con soli circa 33 KB di memoria."

Forse la libreria impiega 33KB di memoria? O è grossa 33KB?

**Comment by andreacostazza** [comment]
E' grossa 33KB

**Comment by andreacostazza** [comment]
ha realizzato una semplice e versatile libreria grande circa 33 KByte

**Comment by andreacostazza** [comment]
07ab072a7cf9f1f5fc301118f519f5443969fb30
