### ISSUE TITLE
Elaborare un indice della tesi e creare le issues corrispondenti

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#7]

**Comment by andreacostazza** [comment]
Apri il file pdf e si vede l'indice, se c'è qualcosa che non va fammi sapere

**Comment by cristianolongo** [comment]
"Il problema delle richieste Cross-Domain." lo metterei nel capitolo 5. Inoltre le sezioni dei capitoli vanno indicate con <numero capitolo>.<numero sezione>. Ma latex le dovrebbe fare così in automatico.

**Comment by cristianolongo** [comment]
Il capitolo 4 deve contenere un riassunto di http://www.dmi.unict.it/~longo/comunect/publicServicesLOD.pdf
