### ISSUE TITLE
"Mostrato in Figura 4 e Figura 5." mostrato cosa?

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#75]
Pag. 14 si trova la frase "Mostrato in Figura 4 e Figura 5." Quale è il soggetto? E' opportuno che tutte le frasi abbiano senso compiuto.

**Comment by andreacostazza** [comment]
In Figura 4 è mostrata la pagina principale del sito web, mentre nella Figura 5 il pannello con i comandi principali.

**Comment by andreacostazza** [comment]
07ab072a7cf9f1f5fc301118f519f5443969fb30
