### ISSUE TITLE
"mentre il predicato è una costante che fa riferimento a rdf." -> "mentre il predicato è una costante."

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#84]
Andrebbe scritto in maniera più articolata ma possiamo anche evitare di citare RDF visto che ne abbiamo parlato qualche sezione prima.

NOTA: eliminare anche la nota a piè di pagina 17.

**Comment by andreacostazza** [comment]
07ab072a7cf9f1f5fc301118f519f5443969fb30
