### ISSUE TITLE
Risultati di una query sparql

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#87]
pag. 18

"I dati ottenuti, facendo una query 18 allo SPARQL, è una tabella molto simile a quelle utilizzate nei
database relazionali in SQL; si tratta di una tabella dove le colonne sono composte dal risultato del
soggetto, del predicato e dell’oggetto."

sostituire con

"Il risultato di una query SPARQL contro un dataset RDF è una tabella molto simile a quelle utilizzate nei database relazionali in SQL; si tratta di una tabella con una colonna per ogni variabile presente nella query. Ogni riga della tabella rappresenta una sostituzione variabile -> valore tale che, se applicata alle triple indicate nella query fa si che le triple ottenute appartengano al dataset contro cui è eseguita la query. "

**Comment by andreacostazza** [comment]
07ab072a7cf9f1f5fc301118f519f5443969fb30
