### ISSUE TITLE
Eliminare sezione sulla clausula FROM

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#89]
E' troppo avanzata e richiederebbe degli approfondimenti sulle query federate. Eliminare il seguente paragrafo:

pag 19

"Come in SQL, anche in SPARQL esiste il comando FROM, contenente un indirizzo IRI, che identifica
tutto il set di dati presenti, dove l’interrogazione dovrà essere svolta; è spesso accompagnato dal
comando NAMED usato per specificare più indirizzi IRI."

**Comment by andreacostazza** [comment]
07ab072a7cf9f1f5fc301118f519f5443969fb30
