### ISSUE TITLE
Aggiungere esempio di Location nella descrizione di LOCN

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#95]
a pagina 21. Vari Frammeti OWL da usare come esempio possono essere estratti dall'ontologia http://opendatahacklab.github.io/odhl.owl

**Comment by andreacostazza** [comment]
inserito 
<rdf:Description rdf:about="http://www.w3.org/ns/org#hasSite"><rdfs:subPropertyOf rdf:resource="http://www.w3.org/ns/locn#location"/></rdf:Description><rdf:Description rdf:about="http://www.w3.org/ns/org#siteAddress"><rdfs:subPropertyOf rdf:resource="http://www.w3.org/ns/locn#address"/></rdf:Description><rdf:Description rdf:about="http://purl.org/NET/c4dm/event.owl#place"><rdfs:subPropertyOf rdf:resource="http://www.w3.org/ns/locn#location"/></rdf:Description>

**Comment by andreacostazza** [comment]
<rdf:Description rdf:about="http://www.w3.org/ns/org#hasSite">
<rdfs:subPropertyOf rdf:resource="http://www.w3.org/ns/locn#location"/></rdf:Description><rdf:Description rdf:about="http://www.w3.org/ns/org#siteAddress"><rdfs:subPropertyOf rdf:resource="http://www.w3.org/ns/locn#address"/></rdf:Description><rdf:Description rdf:about="http://purl.org/NET/c4dm/event.owl#place"><rdfs:subPropertyOf rdf:resource="http://www.w3.org/ns/locn#location"/></rdf:Description>

**Comment by andreacostazza** [comment]
bca222fc3c6c5fad6f8e766ce20f2b84a49c8a41
