### ISSUE TITLE
Descrizione dell'ontologia del comune di Catania

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/cityservices#98]
"Nel progetto è stato utilizzato un vocabolario creato dal Dott.Cristiano Longo che fa
riferimento allo macro struttura del Comune di Catania." 
sostituire con 

"Nel progetto è stata utilizzata una ontologia, resa disponibile attraverso un dataset RDF ed un corrispondente endpoint sparql, che fa riferimento allo macro struttura del Comune di Catania."

**Comment by andreacostazza** [comment]
bca222fc3c6c5fad6f8e766ce20f2b84a49c8a41
